### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by chrislaurie-bs** [4Q-s-r-o/ota_update#28]
When the installation runs it, comes back with "App not installed". There is nothing in the console. 

It seems to get stuck a long time on value 99. In the console i see a few

OTA UPDATE TRACK DOWNLOAD RUNNING 

and then a LOT of 

 OTA UPDATE PAUSED. REASON IS (CHECK AGAINST PAUSED_ CONSTANTS OF DownloadManager: 1

Thereafter, it asks me if I want to install. It starts the installation and then the error above happens.

**Comment by Zhaojing0987** [comment]
Got the same error.In my console, everything works fine, I can see 'OTA UPDATE SUCCESS'.But 'App not installed' because an existing package by the same name with conflicting.

**Comment by MartinHlavna** [comment]
@chrislaurie-bs 

AndroidManager PAUSED_ constant with value 1 is [PAUSED_WAITING_TO_RETRY](https://developer.android.com/reference/android/app/DownloadManager#PAUSED_WAITING_TO_RETRY) 

Looks like the download has crashed for some network reasons. Due to a strange behavior in DownloadManager, we'll receive info about completed download event if it is not successful, so the installation will try to start anyways.

@Zhaojing0987 If I understand correctly it is different app with same package name? Android requires package name to be unique (signed with same private key).

**Comment by ethael** [comment]
Non active issue. closing.
