### ISSUE TITLE
deprecated API

### ISSUE THREAD

**Issue by iamashishk** [4Q-s-r-o/ota_update#60]
Note: F:\flutter\.pub-cache\hosted\pub.dartlang.org\ota_update-3.0.2\android\src\main\java\sk\fourq\otaupdate\OtaUpdatePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by FelixMittermeier** [comment]
More details:

The plugins `ota_update` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by MartinHlavna** [comment]
Thanks for the info. Version 3.1.0 now supports V2 embedding. However for now we will also retain backwards compatibility with V1 embedding (which documentation suggests). However this still prints out warning. 

When flutter will finally remove this API, we will also drop backwards compatibility (indeed we may drop support sooner, this is yet to be decided).
