### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by avecost** [4Q-s-r-o/ota_update#73]
using the latest ota_update, the update app has been downloaded successfully. I am encountering this error on the installation process.

**Comment by MartinHlavna** [comment]
Hello thanks for the report. 

Can you share ```adb logcat``` from installation? It usually has the answer. It is unfortunate that android install does not provide reason for the user.

Some common reasons we have experienced so far:

1. Google play protection - when you do not distribute your app via play store, play protection may interfere with installation. Solution is to either disable play protection (if you can), or you can submit your package for approval manually
2. APK signature is different. This usually happens when you want to replace release build with debug build or vice versa. 
3. APK version (number after + version field) is lower than version already installed. Android will not allow downgrade

**Comment by georgeos** [comment]
Hello @MartinHlavna 
I've tried your suggestions:
1. Disabled Google play protection
2. Used same APK signature. In our case, we're using signingConfigs.debug. 
3. APK version is lower than version installed.

Weird thing is that, we're two developers. For one of us, it's working but not for me.
