### ISSUE TITLE
 Content-length header is missing. Cannot compute progress. 

### ISSUE THREAD

**Issue by skanacodes** [4Q-s-r-o/ota_update#80]
I get The error when am trying to download the apk .so dont get the progress

**Comment by MartinHlavna** [comment]
Hello,
this is issue on your server side. Since HTTP response is not sending length of the file, we cannot compute progress as we don't know what 100% is. 

Install execution should still work though. If you want to use progress, please update your server side and provide Content-Length header with file size of you .apk file.
