### ISSUE TITLE
couldn't use on googlePlay store

### ISSUE THREAD

**Issue by DavidMGT** [4Q-s-r-o/ota_update#94]
![image](https://user-images.githubusercontent.com/12042191/208798414-e349ce59-c4cd-4cd6-836e-89b3438d568f.png)

**Comment by MartinHlavna** [comment]
This package is aimed for projects with deployment outside of the Google Play (e.g. private apps for your clients) so user can still update your app without need to manually download APK.

Since you are deploying with Google Play which will provide updates for you, why do you need to use this package?
Removing permission REQUEST_INSTALL_PACKAGES from manifest would render this package useless.
